name: 'acore-core-build-action'
description: 'GitHub Action for AzerothCore core-build'
author: 'locus313'

outputs:
  configure-os:
    description: "Configure OS output"
    value: ${{ steps.configure_os.outputs.output }}
  config-sh:
    description: "Create conf/config.sh output"
    value: ${{ steps.config_sh.outputs.output }}
  import-db:
    description: "Import DB output"
    value: ${{ steps.import_db.outputs.output }}

runs:
  using: composite
  steps:
    - name: Configure OS
      id: configure_os
      run: |
       CMD=$(source ./acore.sh install-deps ${*} 2>&1)
       CMDExitCode=${?}
       CMD="${CMD//'%'/'%25'}"
       CMD="${CMD//$'\n'/'%0A'}"
       CMD="${CMD//$'\r'/'%0D'}"
       echo "::set-output name=output::${CMD}"
       exit ${CMDExitCode}
      shell: bash
      env:
        CONTINUOUS_INTEGRATION: true
    - name: Create conf/config.sh
      id: config_sh
      run: |
       CMD=$(source ./apps/ci/ci-conf.sh ${*} 2>&1)
       CMDExitCode=${?}
       CMD="${CMD//'%'/'%25'}"
       CMD="${CMD//$'\n'/'%0A'}"
       CMD="${CMD//$'\r'/'%0D'}"
       echo "::set-output name=output::${CMD}"
       exit ${CMDExitCode}
      shell: bash
    - name: Import db
      id: import_db
      run: |
       CMD=$(source ./apps/ci/ci-import-db.sh  2>&1)
       CMDExitCode=${?}
       CMD="${CMD//'%'/'%25'}"
       CMD="${CMD//$'\n'/'%0A'}"
       CMD="${CMD//$'\r'/'%0D'}"
       echo "::set-output name=output::${CMD}"
       exit ${CMDExitCode}
      shell: bash
    - name: Build
      run: source ./apps/ci/ci-compile.sh
      shell: bash
    - name: Dry run
      run: source ./apps/ci/ci-worldserver-dry-run.sh
      shell: bash
    - name: Check startup errors
      run: source ./apps/ci/ci-error-check.sh
      shell: bash
    - name: Run unit tests
      run: source ./apps/ci/ci-run-unit-tests.sh
      shell: bash
