name: 'acore-core-build-action'
description: 'GitHub Action for AzerothCore core-build'
author: 'locus313'

outputs:
  configure-os:
    description: "Configure OS output"
    value: ${{ steps.configure_os.outputs.output }}
  import-db:
    description: "Configure OS output"
    value: ${{ steps.import_db.outputs.output }}

runs:
  using: composite
  steps:
    - name: Configure OS
      id: configure_os
      run: |
       source ./acore.sh install-deps > configure_os.out
       CMD="$(cat configure_os.out)"
       CMD="${CMD//'%'/''%25'}"
       CMD="${CMD//$'\n'/'%0A'}"
       CMD="${CMD//$'\r'/'%0D'}"
       echo "::set-output name=output::$(echo "$CMD")"
      shell: bash
      env:
        CONTINUOUS_INTEGRATION: true
    - name: Create conf/config.sh
      run: source ./apps/ci/ci-conf.sh
      shell: bash
    - name: Import db
      id: import_db
      run: echo "::set-output name=output::$(source ./apps/ci/ci-import-db.sh)"
      shell: bash
    - name: Build
      run: source ./apps/ci/ci-compile.sh
      shell: bash
    - name: Dry run
      run: source ./apps/ci/ci-worldserver-dry-run.sh
      shell: bash
    - name: Check startup errors
      run: source ./apps/ci/ci-error-check.sh
      shell: bash
    - name: Run unit tests
      run: source ./apps/ci/ci-run-unit-tests.sh
      shell: bash
